osx_image: xcode9.2
language: swift

before_install:
  - pod repo update

script:
  - xcodebuild clean build -project DSAKit.xcodeproj -scheme DSAKit -sdk iphonesimulator11.2 ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
