osx_image: xcode9
language: swift
cache:
- bundler
- cocoapods

before_install:
  - pod repo update

script:
  - xcodebuild clean test -quiet -workspace DSAkit.xcworkspace -scheme DSAkit -destination 'platform=iOS Simulator,name=iPhone 8s'

after_success:
  - bash <(curl -s https://codecov.io/bash)